### ISSUE TITLE
Version 2.9 - Scope & Features

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx#359]
# 2.9 Release Overview

_Complementary to [Roadmap](https://github.com/lightspeeddevelopment/lsx/blob/master/roadmap.md)._

### New

- [x] Cover Page Template #384
- [x] LSX Sub-heading Class for Group Blocks #385

### Theme Enhancements & Bug Fixes 

- [x] Fixed the mobile widths.
- [x] Archive blog spacing fixes.
- [x] Improvements on the container block.
- [x] Improvements on the image block.
- [x] Fixed the compatibility with the LSX Blocks "disable title" functionality.
- [x] Fixed the search bar spacing issues. https://github.com/lightspeeddevelopment/lsx/pull/381
- [x] Fixed the margin issue when some titles are too long. https://github.com/lightspeeddevelopment/lsx/pull/386
- [x] Improve the Breadcrumb Placement and Styling https://github.com/lightspeeddevelopment/lsx/pull/381
- [x] Update theme files to support the latest WordPress theme standards and practices #383
- [x] Search bar needs to be reviewed #377
- [x] Reducing the Padding on LSX Buttons #378

### Blog

- [x] Update single blog layout to support block editor first and foremost
- [x] Add LSX Search & FacetWP filtering support to all the Blog archive layouts #364 
- [x] If the title of a post is too long it causes issues on the post header #358

### Block Editor & Block Styling
- [x] Dedicated Styles for Certain Blocks #391 
- [x] Block Theme Support updates #370
- [x] Core block and spacing improvements #373
- [x] Remove older Gutenberg block styling #369

### Yoast SEO 
- [x] Make LSX compatible with Yoast SEO's internal linking blocks #395
- [x] Add styling support for the Yoast SEO plugin HowTo block #363
- [x] Add styling support for the Yoast SEO plugin's HowTo block #362 

### Tribe Events 

- [x] Improved styling for the Tribe Events Community Events forms.
- [x] In the event archive page the banner duplicates every time you switch views #380

### WooCommerce Enhancements
- [x] Added support for the Mix and Match Woocommerce plugin.
- [x] Improved support for Woocommerce Wishlist plugin.
- [x] Improved support for Woocommerce Quick View plugin.
- [x] Merge two WooCommerce panels within the customizer sidebar #387
- [x] Simplify the Cart and Checkout pages #7 

### Sensei

- [x] Text and link order is not correct on the Sensei single lesson notification message #396
- [x] Sensei single lesson placeholder image is broken #397
